package:
  name: bwa
  version: "0.7.8"

build:
  number: 1

source:
  fn: bwa-0.7.8.tar.bz2
  url: http://downloads.sourceforge.net/project/bio-bwa/bwa-0.7.8.tar.bz2
  md5: 51ca7a29907022080398b2b88207e33c

requirements:
  build:
    - gcc   # [not osx]
    - llvm  # [osx]
    - zlib {{CONDA_ZLIB}}*
  run:
    - libgcc  # [not osx]
    - zlib {{CONDA_ZLIB}}*

about:
  home: http://bio-bwa.sourceforge.net
  license: MIT
  summary: The BWA read mapper.
