package:
  name: bwa
  version: "0.5.9"

build:
  number: 1

source:
  fn: bwa-0.5.9.tar.bz2
  url: http://downloads.sourceforge.net/project/bio-bwa/bwa-0.5.9.tar.bz2
  md5: b60719d7f6bc49fd39cbc4e0b6bd787e

requirements:
  build:
    - gcc
    - zlib {{CONDA_ZLIB}}*
  run:
    - libgcc
    - zlib {{CONDA_ZLIB}}*

about:
  home: http://bio-bwa.sourceforge.net
  license: MIT
  summary: The BWA read mapper.
