package:
  name: samtools
  version: 0.1.17

requirements:
  build:
    - gcc
    - pkg-config
    - zlib {{CONDA_ZLIB}}*
  run:
    - pkg-config
    - zlib {{CONDA_ZLIB}}*

source:
  fn: samtools-0.1.17.tar.bz2
  url:
    - http://downloads.sourceforge.net/project/samtools/samtools/0.1.17/samtools-0.1.17.tar.bz2
    - http://download.lab7.io/sources/samtools-0.1.17.tar.bz2
  md5: 9549f7a6bba894766df9c3dd18d61f0b
  patches:
    - makefiles.patch
    - sources.patch

build:
  number: 1

about:
  home: http://samtools.sourceforge.net/
  license: MIT
  license_file: COPYING
  summary: "Library for manipulating alignments in the SAM/BAM format"

test:
  commands:
    - samtools --help

