package:
  name: vt
  version: '2015.11.10'

source:
  fn: vt-15f90de5.tar.gz
  url: https://github.com/atks/vt/archive/15f90de5.tar.gz

build:
  number: 2
  skip: True # [osx]

requirements:
  build:
    - zlib {{CONDA_ZLIB}}*
  run:
    - zlib {{CONDA_ZLIB}}*

test:
  commands:
    - vt

about:
  home: https://github.com/atks/vt
  license: MIT
  summary: A tool set for short variant discovery in genetic sequence data
