package:
  name: bwa
  version: "0.7.3a"

build:
  number: 1

source:
  fn: bwa-0.7.3a.tar.bz2
  url: http://downloads.sourceforge.net/project/bio-bwa/bwa-0.7.3a.tar.bz2
  md5: 7ed9f5d750d26f5bf91cee1fa6f65df2

requirements:
  build:
    - gcc   # [not osx]
    - llvm  # [osx]
    - zlib {{CONDA_ZLIB}}*
  run:
    - libgcc  # [not osx]
    - zlib {{CONDA_ZLIB}}*

test:
  commands:
    - bwa 2>&1 | grep "index sequences"

about:
  home: http://bio-bwa.sourceforge.net
  license: MIT
  summary: The BWA read mapper.
